import CoreGraphics
import Foundation
@testable import Honkumi
import XCTest

final class PDFX4GeneratedPDFTests: XCTestCase {
    private let requiredSizes: Set<CGFloat> = [7, 10, 12, 12.5, 16.5]

    // Catches independently captured timestamps, missing synchronized XMP fields,
    // duplicate or incorrect PDF/X identifiers, and accidental author creation.
    func testCanonicalMetadataBuildsCompleteSynchronizedXMPWithoutAuthor() throws {
        let exportedAt = Date(timeIntervalSince1970: 1_785_888_496.875)
        let metadata = PDFX4DocumentMetadata.make(
            title: "題名 & <確認>",
            documentID: UUID(uuidString: "11111111-2222-3333-4444-555555555555")!,
            exportedAt: exportedAt,
            instanceID: UUID(uuidString: "AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE")!
        )

        let xmp = try PDFX4TestInspector.inspectXMP(
            PDFPrintProduction.pdfX4Profile.xmpMetadataData(for: metadata)
        )

        XCTAssertEqual(metadata.creationDate.timeIntervalSince1970, 1_785_888_496)
        XCTAssertEqual(metadata.modificationDate, metadata.creationDate)
        XCTAssertEqual(xmp.title, "題名 & <確認>")
        XCTAssertEqual(xmp.description, "Print-ready PDF generated by Honkumi")
        XCTAssertEqual(xmp.keywords, "print, novel, Honkumi")
        XCTAssertEqual(xmp.creatorTool, "Honkumi")
        XCTAssertEqual(xmp.producer, "Honkumi")
        XCTAssertEqual(xmp.creatorCount, 0)
        XCTAssertEqual(xmp.pdfXVersionCount, 1)
        XCTAssertEqual(xmp.pdfXConformanceCount, 0)
        XCTAssertEqual(xmp.createDate, "2026-08-05T00:08:16Z")
        XCTAssertEqual(xmp.modifyDate, xmp.createDate)
        XCTAssertEqual(xmp.metadataDate, xmp.modifyDate)
    }

    func testRequiredFontSizesProduceValidStructuresForNormalAndSpreadPDFs() throws {
        let samples = PrintSettingSampleManifest.fontSizeCases().filter {
            requiredSizes.contains($0.document.settings.fontSize)
        }
        XCTAssertEqual(samples.count, requiredSizes.count)
        XCTAssertEqual(Set(samples.map(\.document.settings.fontSize)), requiredSizes)

        for sample in samples {
            let normalURL = try BodyPDFExportService().export(
                document: sample.document,
                subscriptionStatus: .free
            )
            defer { try? FileManager.default.removeItem(at: normalURL) }
            try assertRequiredStructure(at: normalURL, label: "\(sample.fileName) normal")
            try persistArtifactIfRequested(
                sourceURL: normalURL,
                fontSize: sample.document.settings.fontSize,
                kind: "normal"
            )

            let spreadURL = try BodyPDFExportService().exportPreviewPDF(
                document: sample.document,
                subscriptionStatus: .free,
                previewKind: .spread,
                generationID: UUID()
            )
            defer { try? FileManager.default.removeItem(at: spreadURL) }
            try assertRequiredStructure(at: spreadURL, label: "\(sample.fileName) spread")
            try persistArtifactIfRequested(
                sourceURL: spreadURL,
                fontSize: sample.document.settings.fontSize,
                kind: "spread"
            )
        }
    }

    func testXMPStringInspectionDecodesTextAndAttributeEntities() throws {
        let xmp = Data(
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <root attribute="attribute &amp; &lt;decoded&gt;">
              text &amp; &lt;decoded&gt;
              <child><![CDATA[cdata & <decoded>]]></child>
            </root>
            """.utf8
        )

        let values = try PDFX4TestInspector.inspectXMPStrings(xmp)

        XCTAssertTrue(values.contains("attribute & <decoded>"))
        XCTAssertTrue(values.contains { $0.contains("text & <decoded>") })
        XCTAssertTrue(values.contains("cdata & <decoded>"))
    }

    func testOutputIntentInspectionReportsActualNonemptyArrayCount() throws {
        let pdf = PDFTestFixtureBuilder.malformedQuartzStylePDF(
            includeReadablePage: true,
            additionalCatalogEntries:
                " /OutputIntents [<< /Type /OutputIntent >> << /Type /OutputIntent >>]"
        )

        XCTAssertEqual(try PDFX4TestInspector.outputIntentCount(in: pdf), 2)
    }

    // Catches colophon identity and contact values being copied into document metadata.
    // The rendered colophon may legitimately contain these values, so inspect only Info and XMP.
    func testEnabledColophonValuesRemainAbsentFromInfoAndXMP() throws {
        let author = "private-author-&-7E1D6FC8"
        let circle = "private-circle-<2A79B4E5>"
        let contact = "private-contact-81C3@example.invalid"
        let url = "https://private.example.invalid/4D98B2A7"
        var document = ManuscriptDocument(title: "Metadata privacy", body: "本文")
        document.settings.colophon.isEnabled = true
        document.settings.colophon.authorName = author
        document.settings.colophon.circleName = circle
        document.settings.colophon.contact = contact
        document.settings.colophon.websiteURL = url
        document.settings.colophon.showsAuthorName = true
        document.settings.colophon.showsCircleName = true
        document.settings.colophon.showsWebsiteURL = true

        let exportedURL = try BodyPDFExportService().export(
            document: document,
            subscriptionStatus: .free
        )
        defer { try? FileManager.default.removeItem(at: exportedURL) }
        let data = try Data(contentsOf: exportedURL)

        let semantic = try PDFX4TestInspector.inspect(data)
        XCTAssertNil(semantic.infoAuthor)
        XCTAssertEqual(semantic.xmpCreatorCount, 0)

        let xmpValues = try PDFX4TestInspector.xmpStrings(in: data)
        for secret in [author, circle, contact, url] {
            XCTAssertFalse(xmpValues.contains { $0.contains(secret) })
        }
        let infoValues = try PDFX4TestInspector.infoStrings(in: data)
        for secret in [author, circle, contact, url] {
            XCTAssertFalse(infoValues.values.contains { $0.contains(secret) })
        }
    }

    private func assertRequiredStructure(at url: URL, label: String) throws {
        let data = try Data(contentsOf: url)
        let structure = try PDFX4StructureFinalizer.structure(in: data)
        try PDFX4StructureFinalizer.validateReferences(in: structure)

        XCTAssertTrue(
            data.starts(with: Data("%PDF-\(PDFPrintProduction.targetPDFVersion)".utf8)),
            label
        )
        XCTAssertEqual(
            structure.declaredSize,
            (structure.entries.keys.max() ?? -1) + 1,
            label
        )
        XCTAssertNotNil(structure.objectBodies[structure.rootReference], label)
        XCTAssertEqual(data[structure.xrefOffset...].prefix(4), Data("xref".utf8), label)

        for entry in structure.entries.values {
            guard case let .inUse(offset) = entry.kind else { continue }
            XCTAssertGreaterThan(offset, 0, label)
            let header = Data(
                "\(entry.reference.number) \(entry.reference.generation) obj".utf8
            )
            XCTAssertEqual(data[offset...].prefix(header.count), header, label)
        }

        let semantic = try PDFX4TestInspector.inspect(data)
        XCTAssertEqual(semantic.version, "1.6", label)
        XCTAssertTrue(
            semantic.catalogVersion == nil || semantic.catalogVersion == "1.6",
            label
        )
        XCTAssertEqual(semantic.trappedName, "False", label)
        XCTAssertEqual(semantic.outputIntentCount, 1, label)
        XCTAssertEqual(semantic.outputIntentSubtype, "GTS_PDFX", label)
        XCTAssertFalse(semantic.outputConditionIdentifier.isEmpty, label)
        XCTAssertFalse(semantic.registryName.isEmpty, label)
        XCTAssertFalse(
            semantic.outputCondition.isEmpty && semantic.outputIntentInfo.isEmpty,
            label
        )
        XCTAssertEqual(semantic.iccComponentCount, 4, label)
        XCTAssertFalse(semantic.iccData.isEmpty, label)
        XCTAssertEqual(semantic.iccData.subdata(in: 36..<40), Data("acsp".utf8), label)
        XCTAssertTrue(semantic.iccLoadsAsFourComponentColorSpace, label)
        XCTAssertEqual(semantic.pdfXVersionCount, 1, label)
        XCTAssertEqual(semantic.pdfXConformanceCount, 0, label)
        XCTAssertEqual(semantic.infoTitle, semantic.xmpTitle, label)
        XCTAssertEqual(semantic.infoProducer, "Honkumi", label)
        XCTAssertEqual(semantic.infoProducer, semantic.xmpProducer, label)
        XCTAssertEqual(semantic.infoSubject, semantic.xmpDescription, label)
        XCTAssertEqual(semantic.infoKeywords, semantic.xmpKeywords, label)
        XCTAssertEqual(semantic.infoCreator, semantic.xmpCreatorTool, label)
        XCTAssertNil(semantic.infoAuthor, label)
        XCTAssertEqual(semantic.xmpCreatorCount, 0, label)
        XCTAssertEqual(semantic.infoCreationDate, semantic.xmpCreateDateAsDate, label)
        XCTAssertEqual(semantic.infoModificationDate, semantic.xmpModifyDateAsDate, label)
        XCTAssertEqual(semantic.xmpModifyDateAsDate, semantic.xmpMetadataDateAsDate, label)
        XCTAssertFalse(semantic.isEncrypted, label)
        XCTAssertFalse(semantic.hasAcroForm, label)
        XCTAssertFalse(semantic.hasJavaScript, label)
        XCTAssertFalse(semantic.hasEmbeddedFiles, label)
        XCTAssertFalse(semantic.hasExternalReferences, label)
        XCTAssertTrue(semantic.unresolvedColorSpaceNames.isEmpty, label)
        XCTAssertTrue(semantic.embeddedBaseFontNames.contains("BIZUDMincho-Regular"), label)
        XCTAssertTrue(semantic.embeddedBaseFontNames.contains("HiraginoSans-W3"), label)
    }

    private func persistArtifactIfRequested(
        sourceURL: URL,
        fontSize: CGFloat,
        kind: String
    ) throws {
        guard let directory = ProcessInfo.processInfo.environment[
            "HONKUMI_PDF_X4_ARTIFACT_DIR"
        ] else {
            return
        }
        let directoryURL = URL(fileURLWithPath: directory, isDirectory: true)
        try FileManager.default.createDirectory(
            at: directoryURL,
            withIntermediateDirectories: true
        )
        let name = String(format: "font-%04.1f-%@.pdf", Double(fontSize), kind)
        let destination = directoryURL.appendingPathComponent(name)
        try? FileManager.default.removeItem(at: destination)
        try FileManager.default.copyItem(at: sourceURL, to: destination)
    }
}
